### ISSUE TITLE
Centralized configuration

### ISSUE THREAD

**Issue by nopbyte** [Agile-IoT/Architecture#4]
We have observed in our integration efforts with @cskiraly that the same configuration information seems to be required across different micro-services. 

An example of this is that osjs, secure-nodered, or agile-idm require to know the host name (e.g. agilegw.local,  resin.local? etc) mainly to do web redirections between frames and oauth2 endpoints, etc.

Therefore, a unified component used by other components for configuration may be helpful. Any thoughts on how to implement this?

**Comment by craigmulligan** [comment]
As discussed in the call, if it's a runtime config like `hostname` it's best to pass this from the host via docker compose. 

Unfortunately the host os doesn't have hostname set so we'd need to *currently* do it by sshing first and setting it. [like we do the bluetooth](https://github.com/Agile-IoT/agile-stack/blob/master/push.sh#L6). 

One thing I realised after the call is that we probably can't pass the env var up from the host (because the dockercompose commands are built on you localmachine). So if you where to run, expose the hostname it'd likely actually get you laptops hostname. 😢 

I think this is one of the implications of remote configuring docker @cskiraly. This needs some more thought.

**Comment by craigmulligan** [comment]
@nopbyte could you give more detail on the redirect? Is it not possible to use docker-composes local network? You should be able to resolve other services by hitting <container-name>:<port>. eg `http://agile-core:8080`.

**Comment by nopbyte** [comment]
@craig-mulligan the issue is that when an application (OS.js for example) uses the authorization code or  implicit grants (the ones that let you authenticate users using the browser) needs to redirect the user to IDM. This url is visited by the browser outside of the docker container, so it needs to be something understandable for your laptop (this is why I used agilegw.local before).

Also, when IDM relies on external Identity Providers instead of local user name and passwords, such as Google  to authenticate the user, this process happens also with the external Identity Provider.

We also need to have the name for the local network in docker for other purposes, and this is currently working out. For example, when an application (again such as OS.js) receives a token, it needs to query IDM to validate it.  To do this, we use a separate "internal" host name that is http://agile-idm:3000/. In this way the containers can talk to each other.

**Comment by craigmulligan** [comment]
@nopbyte Okay so the browser needs to access a resource but it doesn't know what the host+port is? I solved this in the UI by proxing relative urls to different services based on path [see here](https://github.com/Agile-IoT/agile-ui/blob/master/Caddyfile). So I'd suggest proxying unless you don't have access to the server internals, then we'd need the host name.

**Comment by nopbyte** [comment]
@craig-mulligan the situation is that you also need this host+port combination to be registered with external identity providers such as google, to enable login with them. As we discussed in our Graz meeting, the easiest way to move forward for now seems to be to have an ENV variable that is accessible from the docker compose and the containers (unless I misunderstood something ;-) ) . Could you please add an example to the agile-stack repo, so we can do the changes in the security branch to merge it with master?

**Comment by craigmulligan** [comment]
Hey @nopbyte sorry for the delay, I needed to run some tests. 

resinOS has a bash env `HOSTNAME` set but we don't have access to that because the compose file environment is built on your laptop before sending to the device so it'll actually just get a blank string if you try expose that from the host. 

But i found an approach that should work quite nicely, you can just mount the /etc/hostname from the host and then read that file. 

eg in compose.yml add this to your service: 
```
volumes:
      - /etc/hostname:/etc/hostname
```

Then in your running container you can just read `/etc/hostname` and it'll return the hostname as a string. 

Let me know if this works for you.

**Comment by nopbyte** [comment]
Hey @craig-mulligan ,

This  looks nice. However, it seems this file only would say "resin". What you mean is to concatenate this host in the file with ".local" to use this host to talk to the gateway always? It seems somehow weird to do this. But I think we can do this to be able to merge the security branch with the master from the agile-stack soon

**Comment by craigmulligan** [comment]
No it will say `resin.local`. I don't think it's weird that's often where systems get host info from. We are just replacing the container host name with the host hostname (but you could mount it anywhere). Eventually we will have an agent on the device that is responsible for knowing what service should be running and will inject the right envar.

**Comment by craigmulligan** [comment]
We have a working prototype. Closing.
